// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $api_docid_ from "./routes/api/[docid].ts";
import * as $api_joke from "./routes/api/joke.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $nft_editor from "./routes/nft/editor.tsx";
import * as $search from "./routes/search.tsx";
import * as $subscribe from "./routes/subscribe.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $Editor from "./islands/Editor.tsx";
import * as $NFTMeta from "./islands/NFTMeta.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/api/[docid].ts": $api_docid_,
    "./routes/api/joke.ts": $api_joke,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/nft/editor.tsx": $nft_editor,
    "./routes/search.tsx": $search,
    "./routes/subscribe.tsx": $subscribe,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/Editor.tsx": $Editor,
    "./islands/NFTMeta.tsx": $NFTMeta,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
