// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_middleware from "./routes/api/_middleware.ts";
import * as $api_joke from "./routes/api/joke.ts";
import * as $api_nft_callback from "./routes/api/nft/callback.ts";
import * as $api_nft_contracts from "./routes/api/nft/contracts.ts";
import * as $api_nft_mintable from "./routes/api/nft/mintable.ts";
import * as $api_nft_minted from "./routes/api/nft/minted.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $Counter from "./islands/Counter.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/_middleware.ts": $api_middleware,
    "./routes/api/joke.ts": $api_joke,
    "./routes/api/nft/callback.ts": $api_nft_callback,
    "./routes/api/nft/contracts.ts": $api_nft_contracts,
    "./routes/api/nft/mintable.ts": $api_nft_mintable,
    "./routes/api/nft/minted.ts": $api_nft_minted,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
